version: '3.8'

services:
  db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
